### ISSUE TITLE
Create main application layout and working settings workspace

### ISSUE THREAD

**Issue by Ave44** [UniversityOfGdanskTeamPython/epseon_gui#13]
- [x] topbar
- [x] leftbar
- [x] workspace display panel
- [x] settings workspace
- [x] changable page theme
- [x] changable page language

**Comment by Ave44** [comment]
Current proggres:

![darkTheme](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/assets/92145505/df14fc34-d388-4d53-8fc9-2ab866514c41)
![lightTheme](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/assets/92145505/5a9ee811-9930-403b-88b0-c64e0aaed41b)

**Comment by Argmaster** [comment]
Some thought on layot from meeting 4:

[2023-11-03-Note-00-59_annotated.pdf](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/files/13245892/2023-11-03-Note-00-59_annotated.pdf)

**Comment by Ave44** [comment]
I have added global store for managing application state, using "Redux" according to "ducks" pattern. Additionally I have been working on changing the language in app, and it is mostly done. Moreover I have been working on "workspace selection bar", which is in advanced state of implementation.

current look of application:
![image](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/assets/92145505/f1193a54-0e7d-4f68-9277-60c6c84aeeba)

**Comment by Ave44** [comment]
I have been working on implementing "data generation workspace", which included generating "device cards" based on non-uniform data from backend. Additionally I have added "workspaces" reducer to store. Below is presented current look of application:

![image](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/assets/92145505/88eb9801-cb3a-4428-8a54-4e06ebd6faa0)

**Comment by Ave44** [comment]
I have been working on improving application web interface. I have merged "leftbar" with "topbar", updated look of "topbar" by adding icons and propre styling,

![image](https://github.com/UniversityOfGdanskTeamPython/epseon_gui/assets/92145505/6a75a1b0-bf2a-4e01-b9ad-324e401a3a85)

**Comment by Ave44** [comment]
I have been working on improving GUI responsiveness, added working translation _(currently only "generate workspace" is translated, but translation of rest is just a mater of adding new translation rules to JSON file)_, and specified detailed description of endpoints for backend to create.

**Comment by Ave44** [comment]
I have begun implementing "Preview workspace", including creating interactive plot to display generated data.

![image](https://github.com/UniversityOfGdanskTeamPython/epseon_gui/assets/92145505/97163afa-4105-4882-ad9e-0cf4bce004f8)

**Comment by Ave44** [comment]
I have added working implementation of displaying data on plot and ways to interact with it. User is able to: 
- select which curves to display on plot (it is possible to display multiple curves at once, currently curves have random color)
- speciffy data approximation (how many data points should be merged to one to improve performance)
- select approximation method (average, first, last)
- speciffy range within which data should be contained (minimum & maximum values)

![image](https://github.com/UniversityOfGdanskTeamPython/epseon_gui/assets/92145505/834f2cd5-57df-4839-9d11-1dde177b5fe7)

**Comment by Ave44** [comment]
I have refactored code related to "preview workspace", finished frontend-backend configuration and resolved pre-commit problems.
