### ISSUE TITLE
Design web page layout

### ISSUE THREAD

**Issue by Argmaster** [UniversityOfGdanskTeamPython/epseon_gui#9]
![projekt wstępny plan](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/assets/92145505/d5556e2a-ec87-49fd-8c81-0f681eb9b183)

- fonu changing (size i style)
- translation
- responsive
- Circular, sans-serif

**Comment by Ave44** [comment]
## Design aplikacji V.1

![mainView-svg](https://github.com/UniversityOfGdanskTeamPython/pec_framework_web_app/assets/92145505/2d3e37ea-3caf-4e1d-b693-00113b43d5ac)

**Comment by Argmaster** [comment]
Based on this layout, please create tasks (Issues) representing parts of GUI which have to be developed over the time.
